services:
  - type: web
    name: Casa-C치lida
    env: static
    staticPublishPath: ./dist   # La carpeta con los archivos generados por Vite
    buildCommand: npm install && npm run build  # Este comando construye la aplicaci칩n para producci칩n
    startCommand: npm run preview  # Este comando sirve los archivos de la build en producci칩n
    branch: main
    routes:
      - type: rewrite
        source: '/*'
        destination: '/'
