services:
  - type: web
    name: Casa-Cálida
    env: static
    staticPublishPath: ./dist   # Cambiar a la carpeta 'dist' que es donde Vite guarda los archivos de producción
    buildCommand: npm install && npm run build  # Usar 'npm run build' para producción
    startCommand: npm run preview  # Usar 'npm run preview' para servir los archivos construidos
    branch: main
    routes:
      - type: rewrite
        source: '/*'
        destination: '/'
