services:
  - type: web
    name: Casa-Cálida
    env: static
    staticPublishPath: ./dist   # Asegúrate de que Vite esté generando los archivos en la carpeta 'dist'
    buildCommand: npm install && npm run build  # Cambiar a 'npm run build' para producción
    startCommand: npm run preview  # Usar 'npm run preview' para servir los archivos construidos
    branch: main
    routes:
      - type: rewrite
        source: '/*'
        destination: '/'
